# <https://conda-forge.org/news/2024/01/29/rust-175-osx-sdk/>
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86]
  - '10.12'                # [osx and x86]
MACOSX_SDK_VERSION:  # [osx and x86]
  - '10.12'          # [osx and x86]